baseURL = "https://bucin-kode.github.io/kuliahphp/"
languageCode = "id-ID"
title = "KuliahPHP by bucinkode"
description = "Situs Catatan Belajar PHP di Kuliah"
theme = "one"
DefaultContentLanguage = "id"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 3

[author]
  name = "andikatulusp"
  homepage = "https://bio.link/andikatulusp"

[params]
mainSections = ["posts"]
headTitle = "KuliahPHP"
description = "by Bucinkode"
extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-xxx"></script>'
twitterCards = true
favicon = "https://raw.githubusercontent.com/bucin-kode/kuliahphp/master/IMG_20220109_180928_738.jpg"

[[params.socials]]
name = "ğŸ  Beranda"
link = "https://bucin-kode.github.io/kuliahphp"

[[params.socials]]
name = "ğŸ‘¦ Penulis"
link = "/kuliahphp/about"

[[params.socials]]
name = "ğŸ¤ Kontribusi"
link = "https://github.com/bucin-kode/LearnPHP"

[languages]
  [languages.id]
    contentDir = "content/id"
    languageName = "Indonesia"
    weight = 1